# introduction to Numpy
# NumPy (or Numpy) is a linear Algebra Library for python, the reason it is so importan for Data science with 
# python is that almost all the libraries in the PyDta Ecosystem rely on Numpy as one of their main bulding blockss.

# Numpy is also incredibly fast, as it has binding to C libraries

# GETTING NUMPY INTO YOUR COMPUTER:

# its hightlu recormmended you install python using Anaconda distribution to make sure all underlying dependencies (such as linear Algebra libraries)
# all sync up with the use of a conda install

# if you have Anaconda, install Numpy by going to your tweminal oe command prompt and typing the ff:"

# conda install numpy or
# pip install numpy

# WHAT WE WILL BE USING NUMPY TO DO:

# Numpy arrays are the main way we will use Numpy throughout the course.
# Numpy arrays essentially come in two flavors: vector and matrices.

# Vectors are strickly 1-d arrays and marices are 2-d (but you should note a matrix can still have one row or one column.)


In [ ]:
# python list

my_list = [1,2,3]

In [6]:
import numpy as np

In [7]:
# Numpy array (casted it from python list)
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
# python catested list
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
# catsting it to Numpy arrays, to have a two a 2-d arrays
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# common ways to use Numpy and create arrays so fast and easy to use are:

# using the arange() function, this is like a range() function in python
# the first value is for the starting, the 2nd is the ending, the third is the output in getting the evenly number or odd, (essentially the jumping method)


In [256]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# generating arrays of zeros throughout



In [259]:
np.zeros(3)

array([0., 0., 0.])

# getting a 5x5 matices using a tuple in zeros, remember its a 2-d array



In [260]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# getting arrays of ones.


In [261]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# anothe important build in function in Numpy is the linspace() function
# this returns the evenly spaced numbers over a specified interval.
# note the difference btw a arange is that, arange takes the third digit as the jumping value
# while arange takes the third values as the number of evenly space you want



In [262]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

# creating an identity matrix using Numpy.
# what is an identity matrix?
# this is useful when you're dealing with linear algebra problems, and its basically a
# two dymensional square matrix, meaning the number of rows is same as the column, 
# which has a diagonal of 1's, the rest are 0's, that why it take a s ingle digit as the argument.
# bcos identity matrix must be squared as the output and the p.i


In [263]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# creating arrays with random numbers.
# this is going to return one 1-d array


In [264]:
np.random.rand(9)

array([0.97220194, 0.53687798, 0.12253675, 0.88603216, 0.77606403,
       0.05579018, 0.38315855, 0.72720287, 0.17505944])

# creating 2-d arrys, 
# note while working with a random() method, you don't pass the argument as a tupple


In [265]:
np.random.rand(5,5)

array([[0.29100115, 0.36764156, 0.00608953, 0.30412401, 0.82668224],
       [0.09995069, 0.28707797, 0.69595417, 0.4720391 , 0.26457142],
       [0.03050445, 0.08691802, 0.65458381, 0.68838506, 0.88893113],
       [0.36591063, 0.99705084, 0.38669136, 0.1704701 , 0.8127144 ],
       [0.26959375, 0.32463992, 0.37255215, 0.79863045, 0.42555433]])

# getting a standard normal distribution or guision
# although this is not a normal distribution, by the time we'll get to data visualization we'll see it
# can as well accept two arguments


In [266]:
np.random.randn(4,4)

array([[ 0.85834655, -1.18875599, -1.5815282 ,  1.3851819 ],
       [ 0.22936168,  0.5703024 ,  0.85156873,  0.57434355],
       [-0.14118286,  0.21748096,  2.31792257, -0.79947892],
       [ 0.28963513,  2.31368817,  1.00860503,  1.33886106]])

# the final random we're going to be talking about is the randint(
# 1st = the low argument, 2nd = high argument, 3rd = the total digits u wan to display


In [269]:
np.random.randint(2,5,10)

array([2, 2, 3, 2, 4, 2, 3, 4, 3, 4])

# some few useful attributes and methods of an array. let's create two new array objects



In [270]:
myarr = np.arange(25)

In [271]:
myarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [60]:
ranarr = np.random.randint(0,50,10)

In [61]:
ranarr

array([46, 24, 27, 48,  7, 44, 22, 40, 43, 30])

# note if the argument doesn't match you'll get an error, 5x5=25


In [272]:
myarr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# finding max or min value in an array


In [70]:
ranarr

array([46, 24, 27, 48,  7, 44, 22, 40, 43, 30])

In [71]:
ranarr.max()

48

# the min value



In [273]:
ranarr.min()

7

# getting the actual location of the max, using the arg() function same as the min



In [274]:
ranarr.argmax()

3

In [74]:
ranarr.argmin()

4

# figurering out the shape of a vector.
# (25,) indicating that it's 1-d array


In [275]:
myarr.shape

(25,)

In [276]:
myarr = myarr.reshape(5,5)

In [277]:
myarr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# its now 2-d array


In [278]:
myarr.shape

(5, 5)

In [279]:
# the last attr. for now is the data type which id dtype in Numpy

myarr.dtype

dtype('int32')

# if you don't want to type in np.rand or ........ you can use this function or method insted



In [280]:
from numpy.random import randint

In [281]:
randint(2,20)

3

# NUMPY INDEXING AND SELECTION

In [95]:
my_range = np.arange(0,11)

In [97]:
my_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# selecting a particular value in the array, just like python indexing.



In [282]:
my_range[9]

9

# values in a range. just like python list, you'll use splicing
# with a starting index and stopping index


In [283]:
my_range[0:6]

array([99, 99, 99, 99, 99, 99])

# everthing in without specifying the starting



In [284]:
my_range[:8]

array([99, 99, 99, 99, 99, 99,  6,  7])

In [285]:
my_range[4:]

array([99, 99,  6,  7,  8,  9, 10])

# Numpy arrays is different from normal python bcos they have te ability to broadcast.



In [ ]:
my_range[0:5] = 100

In [104]:
my_range

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [105]:
my_range = np.arange(0,11)

In [106]:
my_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
slice_of_arr = my_range[0:6]

In [108]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

# let's brocast this array



In [286]:
slice_of_arr[:]

array([99, 99, 99, 99, 99, 99])

In [111]:
slice_of_arr[:] = 99

In [112]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

# note the data is not copied rather its just a view of the original array.


In [287]:
my_range

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# now tryin to do the normal copy


In [288]:
my_copy = my_range.copy()

In [289]:
my_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [116]:
my_range

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# since they're thesame now lets brodcast the the arrays copy



In [290]:
my_copy[:] = 100

In [291]:
my_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

# but the originla array my_range is unaffected



In [292]:
my_range

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# INDEXING 2-D ARRAY  OR MATRIC

In [293]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,40]])

In [124]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 40]])

# there are about two general formats for grabbing values in 2-d arrays, and the are:

# (1) double brackets and 
# (2) single bracket with a coma, (this is the most recormmended one to use)


# the first bracket specifies the index of the value, while the 2nd is for the row of the matrics


In [294]:
arr_2d[0]
# arr_2d[0][0]
# arr_2d[1][2]
# arr_2d[2][0]

array([ 5, 10, 15])

# (2) single bracket notation
# the first value specifies the row, while the last specifies the row


In [295]:
arr_2d[0,2]
arr_2d[1,1]

25

# how to grab chunks of arrays: this is done through slice notation
# don't include row row zeros and ones


In [296]:
arr_2d[:2:,1:]

array([[10, 15],
       [25, 30]])

In [297]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

# if you don't understand this don't kill yourself, we won't be using it often, rather the one we're about to learn

# CONDITIONAL SELECTION

In [141]:
arr_selection = np.arange(1,11)

In [142]:
arr_selection

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [144]:
# comparism
bool_arr = arr_selection > 5

In [145]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [146]:
# returning the digits that are true with this conditional patter
arr_selection[bool_arr]

array([ 6,  7,  8,  9, 10])

In [147]:
# well we can do this in a single line
# and this is called a syntax selection which we'll be using throughout this course especially on Pandas
arr_selection[arr_selection > 5]

array([ 6,  7,  8,  9, 10])

In [148]:
# all elements in the array that is less than three

arr_selection[arr_selection < 3]

array([1, 2])

In [149]:
# excercise:use the arange method and create a 10x5 matrices.
# try grabbing [13,14]
#                 [23,24] using bracket notation
excercise_arr = np.arange(50).reshape(5,10)

In [150]:
excercise_arr 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [151]:
# solution
excercise_arr [1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [155]:
excercise_arr [1:3,3:5]

array([[13, 14],
       [23, 24]])

# just as i said ealear don't worry if you don't uderstand muh about this slicing, you won't do it much, just to show you what Numpy can do, instead we'll be grabbing enteire roles or column

In [157]:
# NUMPY OPERATION


# outlines:
1. Array with Array
2. Array with Scalars
3. Universal Array Functiona

# * Array with Array, at this junction there are many mathematical operations that can persformed in this aspect, within an Array with Array

In [168]:
with_arr = np.arange(0,11)

In [169]:
with_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [170]:
# Additional array with array
with_arr + with_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [171]:
# substrations etc. but be careful wit division, avoid error in zero division
with_arr - with_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [172]:
# with_arr / with_arr

In [175]:
# * Array with Scalars: this is the process of broadcasting Array with a particular number or value


# this example adds 100 to each and every value in the array, (scalar brocastin)
with_arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [181]:
# same are multiplication

with_arr ** 100

array([          0,           1,           0,  -818408495,           0,
       -1971132175,           0,  1027218017,           0, -1426542431,
                 0], dtype=int32)

# sometimes NUmpy will output a warning instead of given the right answer to u.

# ZERO DIVISION ERROR

# with_arr / 0

# THE SOLUTION THERE IS TO BE CAREFUL WHILE WORKING WITH MATHEMATICAL OPERATION IN ANY PROGRAMMING LANGUAGE AVOID ZERO DIVISION ERROR

# * Universal Array Function: Numpy come with many Universal Array Function which can be used mathematically and brocast across the entire array

# taking the squaroot of the above arrays



In [301]:
np.sqrt(with_arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [302]:
# calculation the exponential

np.exp(with_arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [185]:
# for maximum you can say array.max() or np.max(array)

np.max(with_arr)

10

In [186]:
with_arr.max()

10

In [187]:
# geting the sin() of an array

np.sin(with_arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [188]:
# cos()
np.cos(with_arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

# log() althoug this will result an error, bcos tring to divide by zero, would actually result -infinity
# np.log(with_arr)

In [192]:
# tan()
np.tan(with_arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

# there are many Universal Array Function online which you can use to perform different kinds of mathematical operation


In [194]:
# NUMPY EXCERCISES

In [195]:
# create an arrys with 10 zeros

In [201]:
# solution.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# creating array with 10 ones

In [202]:
# solution:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [203]:
# creating an array with 10 fives

In [204]:
# solution

np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [205]:
# or
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [206]:
# creating an integer from 10 to 50

In [208]:
# solution
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

# creating evenly integers from 10 to 50

In [210]:
# solution
np.arange(10,51,)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

# create a 3x3 matrix with values ranging from 0 to 8

In [224]:
# solution

ranging = np.arange(9)

In [225]:
ranging

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [226]:
ranging.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [227]:
# or
ranging = np.arange(9).reshape(3,3)

In [228]:
ranging

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# create 3x3 matrix with identical matrix

In [232]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# use Numpy to generate a random number btw 0 and 1

In [241]:
# solution
np.random.rand(1)

array([0.53703583])

# use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution

In [245]:
# solution, this is just a single matri not 5x5, use the shape to see
np.random.randn(25)

array([-1.95352385, -0.05966823,  0.0842837 ,  0.14410455, -0.36030834,
        0.15105702,  2.13866424,  1.70400063, -0.12216759, -0.01081647,
       -0.6868218 ,  1.47031496, -0.08255541, -0.57585986,  0.04388721,
        0.41732153,  0.71583951, -0.60980489,  0.06047102,  0.22586192,
        1.26898833,  1.25871136,  0.36437441,  0.17646428, -0.52340675])

# create thi kind of arrays. tell the kind of matrix its

In [250]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [253]:
# or 
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

# create an array of 20 linearly spaced points btw 0 and 1

In [254]:
# solution

np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])